/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary:       '#1a2d82',
        'navy-dark':   '#0f1a50',
        'navy-hover':  '#243595',
        surface:       '#f4f6fb',
        card:          '#ffffff',
        border:        '#dde2f0',
        text:          '#1a1f3a',
        muted:         '#4a5280',
        hint:          '#8892b8',
        accent:        '#f5b800',
        'accent-dim':  'rgba(245,184,0,0.18)',
        success:       '#16A34A',
        'success-bg':  '#f0fdf4',
        'success-border': '#bbf7d0',
        'success-text':   '#15803d',
        warning:       '#D97706',
        'warning-bg':  '#fff8e0',
        'warning-border': '#f3cf78',
        'warning-text':   '#92400e',
        danger:        '#DC2626',
        'danger-bg':   '#fff4f3',
        'danger-border':'#f5c2be',
        'danger-text': '#b91c1c',
        progility: {
          navy:        '#1a2d82',
          'navy-dark': '#0f1a50',
          'navy-hover':'#243595',
          gold:        '#f5b800',
          'gold-dim':  'rgba(245,184,0,0.18)',
          surface:     '#f4f6fb',
          border:      '#dde2f0',
          text:        '#1a1f3a',
          muted:       '#4a5280',
          hint:        '#8892b8',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
